(()=>{const h=React.createElement,D=window.TSB_DATA,LS='tsb_os_demo_v2';
const nav=['Overview','Pricing Engine','Purchase & Raw Tea','Production & QC','Packaging & Rebuild','Inventory','Franchises','POS','Settlements','Finance & P&L','Reports','Users & Access'];
const access={OWNER:nav,OPERATIONS:['Overview','Inventory','Franchises','POS','Settlements','Reports'],FINANCE:['Overview','Settlements','Finance & P&L','Reports'],WAREHOUSE:['Overview','Purchase & Raw Tea','Production & QC','Packaging & Rebuild','Inventory','Reports'],REGIONAL:['Overview','Franchises','Reports'],FRANCHISE:['Overview','Inventory','POS','Settlements'],CASHIER:['POS']};
const initial={sales:[],purchases:[],production:[],packages:[],transfers:[],franchises:[],expenses:[],settings:{marginTier:'Starter',manualMargin:30,farukTier:'Base',farukManual:20,...D.assumptions}};
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(LS)||'{}')}}catch{return initial}}
function save(s){localStorage.setItem(LS,JSON.stringify(s))}
const money=n=>'৳'+Math.round(Number(n||0)).toLocaleString('en-BD');
const round10=n=>Math.ceil(n/10)*10;
function packCost(cat,g,a){if(cat==='CTC / Black Tea'){if(g===250)return a.ctc250;if(g===500)return a.ctc500;if(g===1000)return a.ctc500*2;if(g===2000)return a.ctc500*4;if(g===5000)return a.ctc500*10}if(g===30)return a.tube30;if(g===50)return a.pouch50;if(g===100)return a.pouch100;if(g===200)return a.pouch100*2;if(g===250)return a.pouch100*2+a.pouch50;return 0}
function economics(p,g,s,margin){const raw=p.costKg*g/1000,pack=packCost(p.category,g,s),waste=raw*(s.wastagePct/100),landed=raw+pack+s.labour+s.overhead+s.logistics+waste,min=round10(landed/(1-(margin/100)-.15));return{raw,pack,waste,landed,min,fr:min*margin/100,company:min*(1-margin/100)}}
function Field({label,value,onChange,type='text',step}){return h('label',{className:'field'},label,h('input',{type,step,value,onChange:e=>onChange(e.target.value)}))}
function Pill({children,kind=''}){return h('span',{className:'pill '+kind},children)}
function Empty({text}){return h('div',{className:'empty'},text)}
function Login({onDemo}){const[email,setEmail]=React.useState('owner@teashop.bd');return h('div',{className:'login'},h('section',{className:'loginIntro'},h('div',{className:'logo'} ,'T'),h('small',null,'TEA SHOP BD · BUSINESS OS'),h('h1',null,'One command center.',h('br'),'Every outlet accountable.'),h('p',null,'Raw tea, production, packaging, inventory, franchise, POS, settlement and finance—under founder control.')),
h('div',{className:'loginCard'},h('div',{className:'logo mini'},'T'),h('h2',null,'Welcome back'),h('p',null,'Production authentication will use server-side password hashing. Use a demo role below while the database gate is being connected.'),h(Field,{label:'Email',value:email,onChange:setEmail}),h('button',{className:'primary',onClick:()=>{const u=D.users.find(x=>x.email===email);u?onDemo(u):alert('Select a configured demo user.')}},'Continue in demo mode →'),h('div',{className:'demoUsers'},h('b',null,'DEMO USERS'),D.users.map(u=>h('button',{key:u.email,onClick:()=>{setEmail(u.email);onDemo(u)}},h('span',null,u.name),h('small',null,u.email))))))}
function Shell(){const[user,setUser]=React.useState(null),[page,setPage]=React.useState('Overview'),[state,setState]=React.useState(load());
React.useEffect(()=>save(state),[state]);if(!user)return h(Login,{onDemo:u=>{setUser(u);setPage(u.role==='CASHIER'?'POS':'Overview')}});
const allowed=access[user.role]||['Overview'];if(!allowed.includes(page))setTimeout(()=>setPage(allowed[0]),0);
return h('div',{className:'app'},h('aside',null,h('div',{className:'brand'},h('div',{className:'logo small'},'T'),h('div',null,h('b',null,'Tea Shop BD'),h('span',null,'Business OS'))),h('div',{className:'rolebox'},h('small',null,'DEMO SESSION'),h('b',null,user.name),h('span',null,user.label)),h('nav',null,allowed.map(n=>h('button',{key:n,className:n===page?'active':'',onClick:()=>setPage(n)},n))),h('button',{className:'logout',onClick:()=>setUser(null)},'Sign out')),
h('main',null,h('header',null,h('div',null,h('small',null,'TEA SHOP BD / '+page.toUpperCase()),h('h2',null,page)),h('div',{className:'headerRight'},h(Pill,{kind:'demo'},'LOCAL DEMO DATA'),h('div',{className:'avatar'},user.name.split(' ').map(x=>x[0]).slice(0,2).join('')))),h(Page,{page,user,state,setState}))}
function Page({page,user,state,setState}){const p={ 'Overview':Overview,'Pricing Engine':Pricing,'Purchase & Raw Tea':Purchases,'Production & QC':Production,'Packaging & Rebuild':Packaging,'Inventory':Inventory,'Franchises':Franchises,'POS':POS,'Settlements':Settlements,'Finance & P&L':Finance,'Reports':Reports,'Users & Access':Users}[page]||Overview;return h(p,{user,state,setState})}
function Overview({state}){const sales=state.sales.reduce((a,b)=>a+b.total,0),margin=state.sales.reduce((a,b)=>a+b.marginEarned,0),exp=state.expenses.reduce((a,b)=>a+Number(b.amount),0),company=sales-margin-exp;return h(React.Fragment,null,
h('section',{className:'hero'},h('div',null,h('small',null,'NETWORK COMMAND CENTER'),h('h1',null,'Founder-controlled growth.'),h('p',null,'Verified sales, accountable stock, outlet health and unit economics in one operating system.')),h('div',{className:'goal'},h('span',null,'NETWORK TARGET'),h('b',null,state.franchises.length+' ',h('em',null,'/ 150')),h('small',null,'outlets configured'))),
h('div',{className:'stats'},h(Card,{t:'Verified POS sales',v:money(sales),s:state.sales.length+' receipts'}),h(Card,{t:'Franchise earned margin',v:money(margin),s:'Only on verified sales'}),h(Card,{t:'Company contribution',v:money(company),s:'Before final tax treatment'}),h(Card,{t:'Active outlets',v:String(state.franchises.filter(x=>x.status!=='closed').length),s:'Configured in this browser'})),
h('div',{className:'twocol'},h('section',{className:'panel'},h(Title,{t:'Franchise margin policy',tag:'25 / 27 / 30 / MANUAL'}),h('div',{className:'tiers'},Object.entries(D.marginTiers).map(([k,v])=>h('div',{key:k},h('b',null,v+'%'),h('span',null,k))))),h('section',{className:'panel'},h(Title,{t:'Md. Omar Faruk performance share',tag:'P&L ONLY'}),h('div',{className:'tiers'},Object.entries(D.farukTiers).map(([k,v])=>h('div',{key:k},h('b',null,v+'%'),h('span',null,k)))))),
h('section',{className:'panel'},h(Title,{t:'A–Z operating chain',tag:'SYSTEM'}),h('div',{className:'flow'},'Purchase → Production/QC → Packaging/Rebuild → Inventory → Franchise → POS Verified Sale → Settlement → Finance/P&L → Faruk Share → Tea Shop BD Net'))) }
function Card({t,v,s}){return h('article',{className:'card'},h('span',null,t),h('b',null,v),h('small',null,s))}
function Title({t,tag}){return h('div',{className:'title'},h('h3',null,t),h(Pill,null,tag))}
function Pricing({state,setState}){const[s,setS]=React.useState(state.settings),[cat,setCat]=React.useState('All'),[margin,setMargin]=React.useState(30);const packs=p=>p.category==='CTC / Black Tea'?[250,500,1000,2000,5000]:[30,50,100,200,250];const list=D.products.filter(p=>cat==='All'||p.category===cat).slice(0,40);function apply(){setState({...state,settings:{...state.settings,...s}})}return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'A–Z PRICING ENGINE'),h('h1',null,'Tea costing & sustainable MRP'),h('p',null,'Authoritative purchase rate + packaging + labour + wastage + overhead + logistics + franchise earning.')),
h('section',{className:'panel controls'},h('div',{className:'controlGrid'},[['tube30','30g Tube'],['pouch50','50g Pouch'],['pouch100','100g Pouch'],['ctc250','CTC 250g pack'],['ctc500','CTC 500g pack'],['labour','Labour'],['overhead','Overhead'],['logistics','Logistics'],['wastagePct','Wastage %']].map(([k,l])=>h(Field,{key:k,label:l,value:s[k],type:'number',step:'.01',onChange:v=>setS({...s,[k]:Number(v)})}))),h('button',{className:'primary fit',onClick:apply},'Save assumptions')),
h('div',{className:'toolbar'},h('select',{value:cat,onChange:e=>setCat(e.target.value)},h('option',null,'All'),[...new Set(D.products.map(p=>p.category))].map(c=>h('option',{key:c},c))),h('label',null,'Franchise % ',h('input',{className:'short',type:'number',value:margin,onChange:e=>setMargin(Number(e.target.value))})),h(Pill,{kind:'success'},D.products.length+' SKUs loaded')),
h('div',{className:'tablewrap'},h('table',null,h('thead',null,h('tr',null,['SKU','Category','৳/kg','Pack','Raw','Packaging','Landed','Planning MRP','Franchise','Company'].map(x=>h('th',{key:x},x)))),h('tbody',null,list.flatMap(p=>packs(p).map(g=>{const e=economics(p,g,state.settings,margin);return h('tr',{key:p.id+'-'+g},h('td',null,h('b',null,p.name)),h('td',null,p.category),h('td',null,money(p.costKg)),h('td',null,g+'g'),h('td',null,money(e.raw)),h('td',null,money(e.pack)),h('td',null,money(e.landed)),h('td',null,h('b',null,money(e.min))),h('td',null,money(e.fr)),h('td',null,money(e.company))) }))))))}
function Purchases({state,setState}){return h(Crud,{title:'Purchase & Raw Tea',desc:'Record supplier purchases and receiving batches.',rows:state.purchases,fields:[['supplier','Supplier'],['product','Tea / material'],['kg','Quantity kg','number'],['rate','Rate / kg','number']],onAdd:x=>setState({...state,purchases:[...state.purchases,{...x,id:Date.now(),date:new Date().toISOString().slice(0,10)}]}),cols:[['date','Date'],['supplier','Supplier'],['product','Item'],['kg','Kg'],['rate','Rate/kg']]})}
function Production({state,setState}){return h(Crud,{title:'Production & QC',desc:'Blend/production batches with input, output and wastage.',rows:state.production,fields:[['batch','Batch no'],['product','Product'],['input','Input kg','number'],['output','Output kg','number']],onAdd:x=>setState({...state,production:[...state.production,{...x,id:Date.now(),waste:Math.max(0,Number(x.input)-Number(x.output))}]}),cols:[['batch','Batch'],['product','Product'],['input','Input kg'],['output','Output kg'],['waste','Wastage kg']]})}
function Packaging({state,setState}){return h(Crud,{title:'Packaging & Rebuild',desc:'Packing/repack jobs from bulk or finished tea into sellable packs.',rows:state.packages,fields:[['job','Job no'],['product','Product'],['pack','Pack grams','number'],['qty','Pack qty','number']],onAdd:x=>setState({...state,packages:[...state.packages,{...x,id:Date.now(),grams:Number(x.pack)*Number(x.qty)}]}),cols:[['job','Job'],['product','Product'],['pack','Pack g'],['qty','Qty'],['grams','Output g']]})}
function Inventory({state}){const purchased=state.purchases.reduce((a,b)=>a+Number(b.kg||0),0),produced=state.production.reduce((a,b)=>a+Number(b.output||0),0),sold=state.sales.reduce((a,b)=>a+Number(b.units||0),0);return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'STOCK CONTROL'),h('h1',null,'Inventory & movement ledger'),h('p',null,'Central stock, franchise stock, transfers, damages and returns.')),h('div',{className:'stats'},h(Card,{t:'Raw tea received',v:purchased.toFixed(2)+' kg',s:'Purchase ledger'}),h(Card,{t:'Produced output',v:produced.toFixed(2)+' kg',s:'Production ledger'}),h(Card,{t:'POS units sold',v:String(sold),s:'Verified receipts'}),h(Card,{t:'Transfers',v:String(state.transfers.length),s:'Location movements'})),h('section',{className:'panel'},h(Title,{t:'Inventory control',tag:'LEDGER'}),h('p',{className:'muted'},'Server database connection will make this an immutable movement ledger. Current browser mode demonstrates the workflow without altering production stock.')))}
function Franchises({state,setState}){const[name,setName]=React.useState(''),[district,setDistrict]=React.useState(''),[tier,setTier]=React.useState('Starter'),[manual,setManual]=React.useState(30);function add(){if(!name)return;const pct=tier==='Manual'?Number(manual):D.marginTiers[tier];setState({...state,franchises:[...state.franchises,{id:Date.now(),name,district,tier,margin:pct,status:'active'}]});setName('');setDistrict('')}return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'FRANCHISE NETWORK'),h('h1',null,'Outlet onboarding & margin control'),h('p',null,'25%, 27%, 30% tiers or Founder-approved manual percentage.')),h('section',{className:'panel formrow'},h(Field,{label:'Outlet name',value:name,onChange:setName}),h(Field,{label:'District / Upazila',value:district,onChange:setDistrict}),h('label',{className:'field'},'Margin tier',h('select',{value:tier,onChange:e=>setTier(e.target.value)},Object.keys(D.marginTiers).map(x=>h('option',{key:x},x)))),tier==='Manual'?h(Field,{label:'Manual %',value:manual,type:'number',onChange:setManual}):null,h('button',{className:'primary fit',onClick:add},'Add outlet')),h(DataTable,{rows:state.franchises,cols:[['name','Outlet'],['district','Location'],['tier','Tier'],['margin','Margin %'],['status','Status']],empty:'No franchise outlets configured yet.'}))}
function POS({state,setState}){const[cart,setCart]=React.useState([]),[margin,setMargin]=React.useState(state.franchises[0]?.margin||25),packs=D.products.slice(0,18).map(p=>{const g=p.category==='CTC / Black Tea'?500:100,e=economics(p,g,state.settings,Number(margin));return{...p,g,price:e.min}});const total=cart.reduce((a,b)=>a+b.price,0);function pay(){if(!cart.length)return;const m=total*Number(margin)/100;setState({...state,sales:[...state.sales,{id:Date.now(),receipt:'TSB-'+Date.now().toString().slice(-6),total,margin:Number(margin),marginEarned:m,units:cart.length,date:new Date().toISOString()}]});setCart([])}return h('div',{className:'pos'},h('section',{className:'panel'},h(Title,{t:'Point of Sale',tag:'VERIFIED SALE'}),h('div',{className:'toolbar'},h('label',null,'Franchise margin % ',h('input',{className:'short',type:'number',value:margin,onChange:e=>setMargin(e.target.value)})),h(Pill,{kind:'success'},'Sale creates earned margin')),h('div',{className:'products'},packs.map(p=>h('button',{key:p.id,onClick:()=>setCart([...cart,p])},h('small',null,p.category),h('b',null,p.name+' '+p.g+'g'),h('strong',null,money(p.price)))))),
h('section',{className:'panel cart'},h(Title,{t:'Current sale',tag:cart.length+' ITEMS'}),cart.length?cart.map((x,i)=>h('div',{className:'line',key:i},h('span',null,x.name),h('b',null,money(x.price)),h('button',{onClick:()=>setCart(cart.filter((_,j)=>j!==i))},'×'))):h(Empty,{text:'Add products to start a sale.'}),h('div',{className:'total'},h('span',null,'Total'),h('b',null,money(total))),h('button',{className:'primary',disabled:!cart.length,onClick:pay},'Complete verified sale →')))}
function Settlements({state}){const grouped={};state.sales.forEach(s=>{const k=s.date.slice(0,7);grouped[k]=grouped[k]||{period:k,sales:0,margin:0,receipts:0};grouped[k].sales+=s.total;grouped[k].margin+=s.marginEarned;grouped[k].receipts++});return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'MONTH-END'),h('h1',null,'Franchise settlement'),h('p',null,'Stock received is not profit. Only verified eligible POS sales create franchise earning.')),h(DataTable,{rows:Object.values(grouped),cols:[['period','Period'],['receipts','Receipts'],['sales','Verified sales',money],['margin','Earned margin',money]],empty:'No verified POS sales yet.'}))}
function Finance({state,setState}){const[name,setName]=React.useState(''),[amount,setAmount]=React.useState(''),[faruk,setFaruk]=React.useState(state.settings.farukTier||'Base');const sales=state.sales.reduce((a,b)=>a+b.total,0),fr=state.sales.reduce((a,b)=>a+b.marginEarned,0),exp=state.expenses.reduce((a,b)=>a+Number(b.amount),0),dist=Math.max(0,sales-fr-exp),pct=faruk==='Manual'?state.settings.farukManual:D.farukTiers[faruk],share=dist*pct/100,net=dist-share;function add(){if(!name||!amount)return;setState({...state,expenses:[...state.expenses,{id:Date.now(),name,amount:Number(amount),date:new Date().toISOString().slice(0,10)}]});setName('');setAmount('')}return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'FINANCE CONTROL'),h('h1',null,'Franchise Division P&L'),h('p',null,'Omar Faruk share is calculated only after approved division costs and expenses.')),h('div',{className:'stats'},h(Card,{t:'Verified revenue',v:money(sales),s:'POS source'}),h(Card,{t:'Franchise earned margin',v:money(fr),s:'Verified sale only'}),h(Card,{t:'Approved expenses',v:money(exp),s:state.expenses.length+' entries'}),h(Card,{t:'Distributable profit',v:money(dist),s:'Before Faruk share'})),h('div',{className:'twocol'},h('section',{className:'panel'},h(Title,{t:'Operating expenses',tag:'DIVISION'}),h('div',{className:'formrow'},h(Field,{label:'Expense',value:name,onChange:setName}),h(Field,{label:'Amount',value:amount,type:'number',onChange:setAmount}),h('button',{className:'primary fit',onClick:add},'Add')),h(DataTable,{rows:state.expenses,cols:[['date','Date'],['name','Expense'],['amount','Amount',money]],empty:'No expenses entered.'})),h('section',{className:'panel'},h(Title,{t:'Omar Faruk performance share',tag:'OWNER CONTROL'}),h('label',{className:'field'},'Tier',h('select',{value:faruk,onChange:e=>setFaruk(e.target.value)},Object.keys(D.farukTiers).map(x=>h('option',{key:x},x)))),h('div',{className:'profitbox'},h('span',null,'Distributable profit'),h('b',null,money(dist)),h('span',null,'Faruk '+pct+'%'),h('b',null,money(share)),h('span',null,'Tea Shop BD remaining'),h('strong',null,money(net))))))}
function Reports({state}){return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'MANAGEMENT REPORTS'),h('h1',null,'Reports & control center'),h('p',null,'Sales, pricing, stock, wastage, settlement and outlet performance.')),h('div',{className:'features'},[['Sales report',state.sales.length+' receipts'],['Purchase report',state.purchases.length+' entries'],['Production report',state.production.length+' batches'],['Franchise report',state.franchises.length+' outlets']].map(x=>h('article',{key:x[0]},h('span',null,'REPORT'),h('b',null,x[0]),h('p',null,x[1]),h('button',null,'Open report →')))))}
function Users(){return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'RBAC'),h('h1',null,'Users & access'),h('p',null,'Founder retains full control; each role sees only its operating scope.')),h(DataTable,{rows:D.users,cols:[['name','User'],['email','Email'],['label','Role']],empty:''}),h('div',{className:'notice'},h('b',null,'Production security gate'),h('span',null,'Passwords are intentionally not stored in this public repository. Database-backed hashing, forced password change and session controls are prepared for the API phase.')))}
function Crud({title,desc,rows,fields,onAdd,cols}){const[form,setForm]=React.useState(Object.fromEntries(fields.map(x=>[x[0],'' ])));function add(){onAdd(form);setForm(Object.fromEntries(fields.map(x=>[x[0],'' ])))}return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'OPERATIONS'),h('h1',null,title),h('p',null,desc)),h('section',{className:'panel formrow'},fields.map(([k,l,t])=>h(Field,{key:k,label:l,value:form[k],type:t||'text',onChange:v=>setForm({...form,[k]:v})})),h('button',{className:'primary fit',onClick:add},'Add record')),h(DataTable,{rows,cols,empty:'No records yet.'}))}
function DataTable({rows,cols,empty}){if(!rows.length)return h(Empty,{text:empty});return h('div',{className:'tablewrap panel'},h('table',null,h('thead',null,h('tr',null,cols.map(c=>h('th',{key:c[0]},c[1])))),h('tbody',null,rows.map((r,i)=>h('tr',{key:r.id||i},cols.map(c=>h('td',{key:c[0]},c[2]?c[2](r[c[0]]):String(r[c[0]]??''))))))))}
ReactDOM.createRoot(document.getElementById('root')).render(h(Shell));
})();