(()=>{const h=React.createElement,D=window.TSB_DATA,LS='tsb_os_demo_v2';
const nav=['Overview','Pricing Engine','Purchase & Raw Tea','Production & QC','Packaging & Rebuild','Inventory','Franchises','POS','Settlements','Finance & P&L','Reports','Users & Access'];
const access={OWNER:nav,OPERATIONS:['Overview','Inventory','Franchises','POS','Settlements','Reports'],FINANCE:['Overview','Settlements','Finance & P&L','Reports'],WAREHOUSE:['Overview','Purchase & Raw Tea','Production & QC','Packaging & Rebuild','Inventory','Reports'],REGIONAL:['Overview','Franchises','Reports'],FRANCHISE:['Overview','Inventory','POS','Settlements'],CASHIER:['POS']};
const initial={sales:[],purchases:[],production:[],packages:[],transfers:[],franchises:[],expenses:[],settings:{marginTier:'Starter',manualMargin:30,farukTier:'Base',farukManual:20,...D.assumptions}};
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(LS)||'{}')}}catch{return initial}}
function save(s){localStorage.setItem(LS,JSON.stringify(s))}
const money=n=>'৳'+Math.round(Number(n||0)).toLocaleString('en-BD');
const round10=n=>Math.ceil(n/10)*10;
function packCost(cat,g,a){if(cat==='CTC / Black Tea'){if(g===250)return a.ctc250;if(g===500)return a.ctc500;if(g===1000)return a.ctc500*2;if(g===2000)return a.ctc500*4;if(g===5000)return a.ctc500*10}if(g===30)return a.tube30;if(g===50)return a.pouch50;if(g===100)return a.pouch100;if(g===200)return a.pouch100*2;if(g===250)return a.pouch100*2+a.pouch50;return 0}
function economics(p,g,s,margin){const raw=p.costKg*g/1000,pack=packCost(p.category,g,s),waste=raw*(s.wastagePct/100),landed=raw+pack+s.labour+s.overhead+s.logistics+waste,min=round10(landed/(1-(margin/100)-.15));return{raw,pack,waste,landed,min,fr:min*margin/100,company:min*(1-margin/100)}}
function Field({label,value,onChange,type='text',step}){return h('label',{className:'field'},label,h('input',{type,step,value,onChange:e=>onChange(e.target.value)}))}
function Pill({children,kind=''}){return h('span',{className:'pill '+kind},children)}
function Empty({text}){return h('div',{className:'empty'},text)}
let csrfToken='';
async function api(route,{method='GET',body}={}){
 const headers={'Accept':'application/json'};
 if(body!==undefined)headers['Content-Type']='application/json';
 if(csrfToken&&method!=='GET')headers['X-CSRF-Token']=csrfToken;
 const parts=String(route).split('?'),routeName=parts.shift(),query=parts.join('?');
 const url='/api/index.php?route='+encodeURIComponent(routeName)+(query?'&'+query:'');
 const res=await fetch(url,{
  method,headers,credentials:'same-origin',body:body===undefined?undefined:JSON.stringify(body)
 });
 let data={};try{data=await res.json()}catch{}
 if(!res.ok||data.ok===false){const err=new Error(data.code||('HTTP_'+res.status));err.code=data.code||'API_ERROR';throw err}
 if(data.csrf)csrfToken=data.csrf;
 return data;
}
function Login({onLogin}){const[email,setEmail]=React.useState('owner@teashop.bd'),[password,setPassword]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await api('login',{method:'POST',body:{email,password}});onLogin(r.user)}catch(err){setError(err.code==='INVALID_LOGIN'?'Email or password is incorrect.':'Unable to sign in right now.')}finally{setBusy(false)}}
return h('div',{className:'login'},h('section',{className:'loginIntro'},h('div',{className:'logo'},'T'),h('small',null,'TEA SHOP BD · BUSINESS OS'),h('h1',null,'One command center.',h('br'),'Every outlet accountable.'),h('p',null,'Raw tea, production, packaging, inventory, franchise, POS, settlement and finance—under founder control.')),
h('form',{className:'loginCard',onSubmit:submit},h('div',{className:'logo mini'},'T'),h('h2',null,'Welcome back'),h('p',null,'Sign in with your Tea Shop BD Business OS account.'),error?h('div',{className:'authError'},error):null,h(Field,{label:'Email',value:email,onChange:setEmail}),h(Field,{label:'Password',value:password,onChange:setPassword,type:'password'}),h('button',{className:'primary',disabled:busy||!email||!password},busy?'Signing in…':'Sign in →'),h('div',{className:'secureNote'},'Secure database authentication · role-based access · audit logging')))}
function ChangePassword({user,onDone,onLogout}){const[current,setCurrent]=React.useState(''),[next,setNext]=React.useState(''),[confirm,setConfirm]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function submit(e){e.preventDefault();setError('');if(next!==confirm){setError('New passwords do not match.');return}if(next.length<10){setError('Use at least 10 characters.');return}setBusy(true);try{const r=await api('password.change',{method:'POST',body:{current_password:current,new_password:next}});onDone(r.user)}catch(err){const m={CURRENT_PASSWORD_INVALID:'Current password is incorrect.',PASSWORD_TOO_SHORT:'Use at least 10 characters.',PASSWORD_WEAK:'Include uppercase, lowercase and a number.',PASSWORD_REUSED:'Choose a different password.'};setError(m[err.code]||'Password could not be changed.')}finally{setBusy(false)}}
return h('div',{className:'login'},h('section',{className:'loginIntro'},h('div',{className:'logo'},'T'),h('small',null,'FIRST LOGIN SECURITY'),h('h1',null,'Set your private password.'),h('p',null,'Your temporary first-login password must be replaced before using the Business OS.')),
h('form',{className:'loginCard',onSubmit:submit},h('div',{className:'logo mini'},'T'),h('h2',null,'Password change required'),h('p',null,user.name+' · '+user.email),error?h('div',{className:'authError'},error):null,h(Field,{label:'Temporary password',value:current,onChange:setCurrent,type:'password'}),h(Field,{label:'New password',value:next,onChange:setNext,type:'password'}),h(Field,{label:'Confirm new password',value:confirm,onChange:setConfirm,type:'password'}),h('button',{className:'primary',disabled:busy||!current||!next||!confirm},busy?'Updating…':'Set new password →'),h('button',{type:'button',className:'textButton',onClick:onLogout},'Sign out')))}
function Loading(){return h('div',{className:'authLoading'},h('div',{className:'logo'},'T'),h('b',null,'Tea Shop BD Business OS'),h('span',null,'Checking secure session…'))}
function Shell(){const[user,setUser]=React.useState(undefined),[page,setPage]=React.useState('Overview'),[state,setState]=React.useState(load());
React.useEffect(()=>save(state),[state]);
React.useEffect(()=>{api('me').then(r=>setUser(r.user)).catch(()=>setUser(null))},[]);
async function logout(){try{await api('logout',{method:'POST',body:{}})}catch{}csrfToken='';setUser(null);setPage('Overview')}
if(user===undefined)return h(Loading);
if(!user)return h(Login,{onLogin:u=>{setUser(u);setPage(u.role==='CASHIER'?'POS':'Overview')}});
if(Number(user.must_change_password)===1)return h(ChangePassword,{user,onDone:u=>setUser(u),onLogout:logout});
const allowed=access[user.role]||['Overview'];if(!allowed.includes(page))setTimeout(()=>setPage(allowed[0]),0);
return h('div',{className:'app'},h('aside',null,h('div',{className:'brand'},h('div',{className:'logo small'},'T'),h('div',null,h('b',null,'Tea Shop BD'),h('span',null,'Business OS'))),h('div',{className:'rolebox'},h('small',null,'SECURE SESSION'),h('b',null,user.name),h('span',null,user.role_name||user.role)),h('nav',null,allowed.map(n=>h('button',{key:n,className:n===page?'active':'',onClick:()=>setPage(n)},n))),h('button',{className:'logout',onClick:logout},'Sign out')),
h('main',null,h('header',null,h('div',null,h('small',null,'TEA SHOP BD / '+page.toUpperCase()),h('h2',null,page)),h('div',{className:'headerRight'},h(Pill,{kind:'success'},'LIVE DATABASE'),h('div',{className:'avatar'},user.name.split(' ').map(x=>x[0]).slice(0,2).join('')))),h(Page,{page,user,state,setState})))}
function Page({page,user,state,setState}){const p={ 'Overview':Overview,'Pricing Engine':Pricing,'Purchase & Raw Tea':Purchases,'Production & QC':Production,'Packaging & Rebuild':Packaging,'Inventory':Inventory,'Franchises':Franchises,'POS':POS,'Settlements':Settlements,'Finance & P&L':Finance,'Reports':Reports,'Users & Access':Users}[page]||Overview;return h(p,{user,state,setState})}
function Overview(){const[data,setData]=React.useState(null),[error,setError]=React.useState('');
React.useEffect(()=>{api('dashboard').then(setData).catch(()=>setError('Live dashboard could not be loaded.'))},[]);
const sales=data?.verified_sales||0,margin=data?.franchise_earned_margin||0,company=data?.company_contribution||0,outlets=data?.active_outlets||0,receipts=data?.receipts||0;
return h(React.Fragment,null,
h('section',{className:'hero'},h('div',null,h('small',null,'NETWORK COMMAND CENTER'),h('h1',null,'Founder-controlled growth.'),h('p',null,'Verified sales, accountable stock, outlet health and unit economics in one operating system.')),h('div',{className:'goal'},h('span',null,'NETWORK TARGET'),h('b',null,outlets+' ',h('em',null,'/ 150')),h('small',null,'active outlets'))),
error?h('div',{className:'authError'},error):null,
h('div',{className:'stats'},h(Card,{t:'Verified POS sales',v:money(sales),s:receipts+' receipts'}),h(Card,{t:'Franchise earned margin',v:money(margin),s:'Only on verified eligible sales'}),h(Card,{t:'Company contribution',v:money(company),s:'After franchise margin & expenses'}),h(Card,{t:'Active outlets',v:String(outlets),s:'Live database'})),
h('div',{className:'twocol'},h('section',{className:'panel'},h(Title,{t:'Franchise margin policy',tag:'25 / 27 / 30 / MANUAL'}),h('div',{className:'tiers'},Object.entries(D.marginTiers).map(([k,v])=>h('div',{key:k},h('b',null,v+'%'),h('span',null,k))))),h('section',{className:'panel'},h(Title,{t:'Md. Omar Faruk performance share',tag:'P&L ONLY'}),h('div',{className:'tiers'},Object.entries(D.farukTiers).map(([k,v])=>h('div',{key:k},h('b',null,v+'%'),h('span',null,k)))),h('p',{className:'muted'},'Calculated only on positive distributable Franchise Division profit.'))),
h('section',{className:'panel'},h(Title,{t:'A–Z operating chain',tag:'SYSTEM'}),h('div',{className:'flow'},'Purchase → Production/QC → Packaging/Rebuild → Inventory → Franchise → POS Verified Sale → Settlement → Finance/P&L → Faruk Share → Tea Shop BD Net')))}
function Card({t,v,s}){return h('article',{className:'card'},h('span',null,t),h('b',null,v),h('small',null,s))}
function Title({t,tag}){return h('div',{className:'title'},h('h3',null,t),h(Pill,null,tag))}
function Pricing({state,setState}){const[s,setS]=React.useState(state.settings),[cat,setCat]=React.useState('All'),[margin,setMargin]=React.useState(30);const packs=p=>p.category==='CTC / Black Tea'?[250,500,1000,2000,5000]:[30,50,100,200,250];const list=D.products.filter(p=>cat==='All'||p.category===cat).slice(0,40);function apply(){setState({...state,settings:{...state.settings,...s}})}return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'A–Z PRICING ENGINE'),h('h1',null,'Tea costing & sustainable MRP'),h('p',null,'Authoritative purchase rate + packaging + labour + wastage + overhead + logistics + franchise earning.')),
h('section',{className:'panel controls'},h('div',{className:'controlGrid'},[['tube30','30g Tube'],['pouch50','50g Pouch'],['pouch100','100g Pouch'],['ctc250','CTC 250g pack'],['ctc500','CTC 500g pack'],['labour','Labour'],['overhead','Overhead'],['logistics','Logistics'],['wastagePct','Wastage %']].map(([k,l])=>h(Field,{key:k,label:l,value:s[k],type:'number',step:'.01',onChange:v=>setS({...s,[k]:Number(v)})}))),h('button',{className:'primary fit',onClick:apply},'Save assumptions')),
h('div',{className:'toolbar'},h('select',{value:cat,onChange:e=>setCat(e.target.value)},h('option',null,'All'),[...new Set(D.products.map(p=>p.category))].map(c=>h('option',{key:c},c))),h('label',null,'Franchise % ',h('input',{className:'short',type:'number',value:margin,onChange:e=>setMargin(Number(e.target.value))})),h(Pill,{kind:'success'},D.products.length+' SKUs loaded')),
h('div',{className:'tablewrap'},h('table',null,h('thead',null,h('tr',null,['SKU','Category','৳/kg','Pack','Raw','Packaging','Landed','Planning MRP','Franchise','Company'].map(x=>h('th',{key:x},x)))),h('tbody',null,list.flatMap(p=>packs(p).map(g=>{const e=economics(p,g,state.settings,margin);return h('tr',{key:p.id+'-'+g},h('td',null,h('b',null,p.name)),h('td',null,p.category),h('td',null,money(p.costKg)),h('td',null,g+'g'),h('td',null,money(e.raw)),h('td',null,money(e.pack)),h('td',null,money(e.landed)),h('td',null,h('b',null,money(e.min))),h('td',null,money(e.fr)),h('td',null,money(e.company))) }))))))}
function Purchases(){const[rows,setRows]=React.useState([]),[products,setProducts]=React.useState([]),[supplier,setSupplier]=React.useState(''),[pid,setPid]=React.useState(''),[kg,setKg]=React.useState(''),[rate,setRate]=React.useState(''),[batch,setBatch]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function loadLive(){try{const[a,b]=await Promise.all([api('purchases'),api('products')]);setRows(a.purchases||[]);setProducts(b.products||[]);if(!pid&&b.products?.[0])setPid(String(b.products[0].id))}catch(e){setError('Purchase data could not be loaded.')}}
React.useEffect(()=>{loadLive()},[]);
async function add(){if(!supplier||!pid||Number(kg)<=0)return;setBusy(true);setError('');try{await api('purchase.create',{method:'POST',body:{supplier,product_id:Number(pid),kg:Number(kg),rate:Number(rate||0),batch_no:batch}});setSupplier('');setKg('');setRate('');setBatch('');await loadLive()}catch(e){setError('Purchase could not be saved: '+(e.code||'ERROR'))}finally{setBusy(false)}}
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'RAW TEA PROCUREMENT'),h('h1',null,'Purchase & Raw Tea'),h('p',null,'Supplier receiving, GRN, batch traceability and purchase-rate history.')),error?h('div',{className:'authError'},error):null,
h('section',{className:'panel formrow'},h(Field,{label:'Supplier',value:supplier,onChange:setSupplier}),h('label',{className:'field'},'Tea / product',h('select',{value:pid,onChange:e=>setPid(e.target.value)},products.map(p=>h('option',{key:p.id,value:p.id},p.name+' · '+money(p.purchase_cost_per_kg)+'/kg')))),h(Field,{label:'Quantity kg',value:kg,onChange:setKg,type:'number'}),h(Field,{label:'Rate / kg',value:rate,onChange:setRate,type:'number'}),h(Field,{label:'Batch / lot',value:batch,onChange:setBatch}),h('button',{className:'primary fit',disabled:busy,onClick:add},busy?'Saving…':'Create GRN')),
h(DataTable,{rows,cols:[['date','Date'],['reference_no','GRN'],['supplier','Supplier'],['product','Tea'],['kg','Kg'],['rate','Rate/kg',money],['batch_no','Batch']],empty:'No purchase receipts yet.'}))}
function Production(){const[rows,setRows]=React.useState([]),[products,setProducts]=React.useState([]),[pid,setPid]=React.useState(''),[batch,setBatch]=React.useState(''),[input,setInput]=React.useState(''),[output,setOutput]=React.useState(''),[qc,setQc]=React.useState('pass'),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function loadLive(){try{const[a,b]=await Promise.all([api('production'),api('products')]);setRows(a.production||[]);setProducts(b.products||[]);if(!pid&&b.products?.[0])setPid(String(b.products[0].id))}catch{setError('Production data could not be loaded.')}}
React.useEffect(()=>{loadLive()},[]);
async function add(){if(!pid||Number(input)<=0||Number(output)<0)return;setBusy(true);setError('');try{await api('production.create',{method:'POST',body:{product_id:Number(pid),batch_no:batch,input:Number(input),output:Number(output),qc_status:qc}});setBatch('');setInput('');setOutput('');await loadLive()}catch(e){setError('Production batch could not be saved: '+(e.code||'ERROR'))}finally{setBusy(false)}}
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'PRODUCTION CONTROL'),h('h1',null,'Production & QC'),h('p',null,'Input/output yield, wastage and QC status recorded to the live database.')),error?h('div',{className:'authError'},error):null,
h('section',{className:'panel formrow'},h('label',{className:'field'},'Product',h('select',{value:pid,onChange:e=>setPid(e.target.value)},products.map(p=>h('option',{key:p.id,value:p.id},p.name)))),h(Field,{label:'Batch no (optional)',value:batch,onChange:setBatch}),h(Field,{label:'Input kg',value:input,onChange:setInput,type:'number'}),h(Field,{label:'Output kg',value:output,onChange:setOutput,type:'number'}),h('label',{className:'field'},'QC',h('select',{value:qc,onChange:e=>setQc(e.target.value)},['pending','pass','hold','reject'].map(x=>h('option',{key:x},x)))),h('button',{className:'primary fit',disabled:busy,onClick:add},busy?'Saving…':'Save batch')),
h(DataTable,{rows,cols:[['batch_no','Batch'],['product','Product'],['input','Input kg'],['output','Output kg'],['waste','Wastage kg'],['qc_status','QC'],['produced_at','Produced']],empty:'No production batches yet.'}))}
function Packaging(){const[rows,setRows]=React.useState([]),[products,setProducts]=React.useState([]),[pid,setPid]=React.useState(''),[grams,setGrams]=React.useState(500),[qty,setQty]=React.useState(''),[mrp,setMrp]=React.useState(''),[batch,setBatch]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function loadLive(){try{const[a,b]=await Promise.all([api('packaging'),api('products')]);setRows(a.packaging||[]);setProducts(b.products||[]);if(!pid&&b.products?.[0]){setPid(String(b.products[0].id));setGrams(b.products[0].category==='CTC / Black Tea'?500:100)}}catch{setError('Packaging data could not be loaded.')}}
React.useEffect(()=>{loadLive()},[]);
const product=products.find(p=>String(p.id)===String(pid));const allowed=product?.category==='CTC / Black Tea'?[250,500,1000,2000,5000]:[30,50,100,200,250];
function chooseProduct(v){setPid(v);const p=products.find(x=>String(x.id)===String(v));setGrams(p?.category==='CTC / Black Tea'?500:100)}
async function add(){if(!pid||Number(qty)<=0)return;setBusy(true);setError('');try{await api('packaging.create',{method:'POST',body:{product_id:Number(pid),grams:Number(grams),qty:Number(qty),mrp:Number(mrp||0),batch_no:batch,labour_cost:0,sealing_cost:0,other_cost:0}});setQty('');setMrp('');setBatch('');await loadLive()}catch(e){setError('Packaging job could not be saved: '+(e.code||'ERROR'))}finally{setBusy(false)}}
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'FINISHED GOODS'),h('h1',null,'Packaging & Rebuild'),h('p',null,'Pack-size rules, finished stock creation and batch traceability.')),error?h('div',{className:'authError'},error):null,
h('section',{className:'panel formrow'},h('label',{className:'field'},'Product',h('select',{value:pid,onChange:e=>chooseProduct(e.target.value)},products.map(p=>h('option',{key:p.id,value:p.id},p.name)))),h('label',{className:'field'},'Pack size',h('select',{value:grams,onChange:e=>setGrams(Number(e.target.value))},allowed.map(g=>h('option',{key:g,value:g},g+'g')))),h(Field,{label:'Pack quantity',value:qty,onChange:setQty,type:'number'}),h(Field,{label:'MRP / pack',value:mrp,onChange:setMrp,type:'number'}),h(Field,{label:'Batch / lot',value:batch,onChange:setBatch}),h('button',{className:'primary fit',disabled:busy,onClick:add},busy?'Saving…':'Complete packaging')),
h(DataTable,{rows,cols:[['job_no','Job'],['product','Product'],['pack','Pack g'],['qty','Qty'],['grams','Output g'],['batch_no','Batch'],['completed_at','Completed']],empty:'No packaging jobs yet.'}))}
function Inventory({user}){const[data,setData]=React.useState({stock:[]}),[franchises,setFranchises]=React.useState([]),[fid,setFid]=React.useState(''),[packId,setPackId]=React.useState(''),[qty,setQty]=React.useState(''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function loadLive(){try{const[a,b]=await Promise.all([api('inventory'),api('franchises')]);setData(a);setFranchises(b.franchises||[]);if(!packId&&a.stock?.[0])setPackId(String(a.stock[0].pack_id));if(!fid&&b.franchises?.[0])setFid(String(b.franchises[0].id))}catch{setError('Inventory could not be loaded.')}}
React.useEffect(()=>{loadLive()},[]);
const canTransfer=['OWNER','WAREHOUSE','OPERATIONS'].includes(user.role);
async function transfer(){if(!fid||!packId||Number(qty)<=0)return;setBusy(true);setError('');try{await api('inventory.transfer.create',{method:'POST',body:{franchise_id:Number(fid),product_pack_id:Number(packId),qty:Number(qty)}});setQty('');await loadLive()}catch(e){setError(e.code==='INSUFFICIENT_CENTRAL_STOCK'?'Not enough central stock for this transfer.':'Stock transfer failed: '+(e.code||'ERROR'))}finally{setBusy(false)}}
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'STOCK CONTROL'),h('h1',null,'Inventory & movement ledger'),h('p',null,'Central finished goods, outlet transfers and stock accountability.')),error?h('div',{className:'authError'},error):null,
h('div',{className:'stats'},h(Card,{t:'Raw tea received',v:Number(data.raw_received_kg||0).toFixed(2)+' kg',s:'Purchase ledger'}),h(Card,{t:'QC-passed output',v:Number(data.produced_kg||0).toFixed(2)+' kg',s:'Production ledger'}),h(Card,{t:'Recorded wastage',v:Number(data.wastage_kg||0).toFixed(2)+' kg',s:'Production variance'}),h(Card,{t:'Finished stock lines',v:String((data.stock||[]).length),s:'Central inventory'})),
canTransfer?h('section',{className:'panel formrow'},h('label',{className:'field'},'Finished pack',h('select',{value:packId,onChange:e=>setPackId(e.target.value)},(data.stock||[]).map(x=>h('option',{key:x.pack_id,value:x.pack_id},x.product+' '+x.pack+'g · stock '+x.qty)))),h('label',{className:'field'},'Franchise outlet',h('select',{value:fid,onChange:e=>setFid(e.target.value)},franchises.map(x=>h('option',{key:x.id,value:x.id},x.name)))),h(Field,{label:'Transfer qty',value:qty,onChange:setQty,type:'number'}),h('button',{className:'primary fit',disabled:busy||!(data.stock||[]).length||!franchises.length,onClick:transfer},busy?'Transferring…':'Transfer to outlet')):null,
h(DataTable,{rows:data.stock||[],cols:[['product','Product'],['category','Category'],['pack','Pack g'],['qty','Central stock'],['mrp','MRP',money]],empty:'No finished goods stock yet. Complete a packaging job to create stock.'}))}
function Franchises({user}){const[rows,setRows]=React.useState([]),[name,setName]=React.useState(''),[district,setDistrict]=React.useState(''),[tier,setTier]=React.useState('Starter'),[manual,setManual]=React.useState(30),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function loadRows(){try{const r=await api('franchises');setRows(r.franchises||[])}catch{setError('Could not load franchise outlets.')}}
React.useEffect(()=>{loadRows()},[]);
async function add(){if(!name||user.role!=='OWNER')return;setBusy(true);setError('');try{const pct=tier==='Manual'?Number(manual):D.marginTiers[tier];await api('franchise.create',{method:'POST',body:{code:'TSB-'+Date.now().toString().slice(-7),name,district,margin_mode:tier==='Manual'?'manual':'tier',margin_tier:tier,margin_percent:pct}});setName('');setDistrict('');await loadRows()}catch(e){setError(e.code==='OWNER_REQUIRED'?'Only Founder can create outlets.':'Outlet could not be created.')}finally{setBusy(false)}}
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'FRANCHISE NETWORK'),h('h1',null,'Outlet onboarding & margin control'),h('p',null,'25%, 27%, 30% tiers or Founder-approved manual percentage.')),error?h('div',{className:'authError'},error):null,user.role==='OWNER'?h('section',{className:'panel formrow'},h(Field,{label:'Outlet name',value:name,onChange:setName}),h(Field,{label:'District / Upazila',value:district,onChange:setDistrict}),h('label',{className:'field'},'Margin tier',h('select',{value:tier,onChange:e=>setTier(e.target.value)},Object.keys(D.marginTiers).map(x=>h('option',{key:x},x)))),tier==='Manual'?h(Field,{label:'Manual %',value:manual,type:'number',onChange:setManual}):null,h('button',{className:'primary fit',disabled:busy,onClick:add},busy?'Saving…':'Add outlet')):null,
h(DataTable,{rows,cols:[['code','Code'],['name','Outlet'],['district','District'],['upazila','Upazila'],['margin_tier','Tier'],['margin_percent','Margin %'],['status','Status']],empty:'No franchise outlets configured yet.'}))}
function POS(){const[cart,setCart]=React.useState([]),[franchises,setFranchises]=React.useState([]),[stock,setStock]=React.useState([]),[fid,setFid]=React.useState(''),[busy,setBusy]=React.useState(false),[msg,setMsg]=React.useState('');
React.useEffect(()=>{api('franchises').then(r=>{const rows=(r.franchises||[]).filter(x=>x.status!=='closed');setFranchises(rows);if(rows[0])setFid(String(rows[0].id))}).catch(()=>{})},[]);
React.useEffect(()=>{if(!fid){setStock([]);return}api('inventory.franchise?franchise_id='+encodeURIComponent(fid)).then(r=>setStock(r.stock||[])).catch(()=>setStock([]))},[fid]);
function addItem(p){const found=cart.find(x=>x.pack_id===p.pack_id);const current=found?.qty||0;if(current>=Number(p.qty))return;setCart(found?cart.map(x=>x.pack_id===p.pack_id?{...x,qty:x.qty+1}:x):[...cart,{...p,qty:1}])}
function removeOne(id){const found=cart.find(x=>x.pack_id===id);if(!found)return;setCart(found.qty<=1?cart.filter(x=>x.pack_id!==id):cart.map(x=>x.pack_id===id?{...x,qty:x.qty-1}:x))}
const total=cart.reduce((a,b)=>a+Number(b.mrp)*Number(b.qty),0);
async function pay(){if(!cart.length||!fid)return;setBusy(true);setMsg('');try{const r=await api('sale.create',{method:'POST',body:{franchise_id:Number(fid),payment_method:'cash',items:cart.map(x=>({product_pack_id:Number(x.pack_id),qty:Number(x.qty)}))}});setCart([]);setMsg('Sale saved · '+r.receipt+' · total '+money(r.gross_amount)+' · franchise earned '+money(r.earned_margin));const inv=await api('inventory.franchise?franchise_id='+encodeURIComponent(fid));setStock(inv.stock||[])}catch(e){setMsg('Sale could not be saved: '+(e.code||'ERROR'))}finally{setBusy(false)}}
return h('div',{className:'pos'},h('section',{className:'panel'},h(Title,{t:'Point of Sale',tag:'LIVE OUTLET STOCK'}),franchises.length?h('div',{className:'toolbar'},h('label',{className:'field'},'Outlet',h('select',{value:fid,onChange:e=>{setFid(e.target.value);setCart([]);setMsg('')}},franchises.map(x=>h('option',{key:x.id,value:x.id},x.name+' · '+x.margin_percent+'%')))),h(Pill,{kind:'success'},stock.length+' stock lines')):h('div',{className:'notice'},h('b',null,'Outlet required'),h('span',null,'Founder must create an outlet first.')),
stock.length?h('div',{className:'products'},stock.map(p=>h('button',{key:p.pack_id,onClick:()=>addItem(p)},h('small',null,p.category),h('b',null,p.product+' '+p.pack+'g'),h('strong',null,money(p.mrp)),h('span',{className:'stockMeta'},'Stock '+p.qty)))):h(Empty,{text:fid?'No stock at this outlet. Transfer finished goods from Inventory first.':'Select an outlet.'})),
h('section',{className:'panel cart'},h(Title,{t:'Current sale',tag:cart.reduce((a,b)=>a+b.qty,0)+' ITEMS'}),msg?h('div',{className:'notice'},msg):null,cart.length?cart.map(x=>h('div',{className:'line',key:x.pack_id},h('span',null,x.product+' '+x.pack+'g × '+x.qty),h('b',null,money(Number(x.mrp)*x.qty)),h('button',{onClick:()=>removeOne(x.pack_id)},'−'))):h(Empty,{text:'Add products from available outlet stock.'}),h('div',{className:'total'},h('span',null,'Total'),h('b',null,money(total))),h('button',{className:'primary',disabled:busy||!cart.length||!fid,onClick:pay},busy?'Saving sale…':'Complete verified sale →')))}
function Settlements(){const[rows,setRows]=React.useState([]),[error,setError]=React.useState('');
React.useEffect(()=>{api('settlement.summary').then(r=>setRows(r.periods||[])).catch(()=>setError('Settlement summary could not be loaded.'))},[]);
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'MONTH-END'),h('h1',null,'Franchise settlement'),h('p',null,'Stock received is not profit. Only verified eligible POS sales create franchise earning.')),error?h('div',{className:'authError'},error):null,h(DataTable,{rows,cols:[['period','Period'],['receipts','Receipts'],['sales','Verified sales',money],['margin','Earned margin',money]],empty:'No verified POS sales yet.'}))}
function Finance(){const[summary,setSummary]=React.useState({}),[expenses,setExpenses]=React.useState([]),[name,setName]=React.useState(''),[amount,setAmount]=React.useState(''),[faruk,setFaruk]=React.useState('Base'),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
async function loadLive(){try{const[a,b]=await Promise.all([api('finance.summary'),api('expenses')]);setSummary(a);setExpenses(b.expenses||[])}catch{setError('Finance data could not be loaded.')}}
React.useEffect(()=>{loadLive()},[]);
const sales=Number(summary.verified_sales||0),fr=Number(summary.franchise_earned_margin||0),exp=Number(summary.approved_expenses||0),dist=Number(summary.distributable_profit||0),pct=D.farukTiers[faruk]||15,share=dist*pct/100,net=dist-share;
async function add(){if(!name||!amount)return;setBusy(true);setError('');try{await api('expense.create',{method:'POST',body:{name,amount:Number(amount)}});setName('');setAmount('');await loadLive()}catch(e){setError(e.code==='ROLE_DENIED'?'Finance access required.':'Expense could not be saved.')}finally{setBusy(false)}}
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'FINANCE CONTROL'),h('h1',null,'Franchise Division P&L'),h('p',null,'Omar Faruk share is calculated only after approved division costs and expenses.')),error?h('div',{className:'authError'},error):null,h('div',{className:'stats'},h(Card,{t:'Verified revenue',v:money(sales),s:'POS source'}),h(Card,{t:'Franchise earned margin',v:money(fr),s:'Verified sales only'}),h(Card,{t:'Approved expenses',v:money(exp),s:expenses.length+' entries'}),h(Card,{t:'Distributable profit',v:money(dist),s:'Before Faruk share'})),
h('div',{className:'twocol'},h('section',{className:'panel'},h(Title,{t:'Operating expenses',tag:'LIVE LEDGER'}),h('div',{className:'formrow'},h(Field,{label:'Expense',value:name,onChange:setName}),h(Field,{label:'Amount',value:amount,type:'number',onChange:setAmount}),h('button',{className:'primary fit',disabled:busy,onClick:add},busy?'Saving…':'Add')),h(DataTable,{rows:expenses,cols:[['date','Date'],['name','Expense'],['amount','Amount',money]],empty:'No operating expenses entered.'})),h('section',{className:'panel'},h(Title,{t:'Omar Faruk performance share',tag:'OWNER POLICY'}),h('label',{className:'field'},'Tier',h('select',{value:faruk,onChange:e=>setFaruk(e.target.value)},['Base','Growth','Elite'].map(x=>h('option',{key:x},x)))),h('div',{className:'profitbox'},h('span',null,'Distributable profit'),h('b',null,money(dist)),h('span',null,'Faruk '+pct+'%'),h('b',null,money(share)),h('span',null,'Tea Shop BD remaining'),h('strong',null,money(net))))))}
function Reports({state}){return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'MANAGEMENT REPORTS'),h('h1',null,'Reports & control center'),h('p',null,'Sales, pricing, stock, wastage, settlement and outlet performance.')),h('div',{className:'features'},[['Sales report',state.sales.length+' receipts'],['Purchase report',state.purchases.length+' entries'],['Production report',state.production.length+' batches'],['Franchise report',state.franchises.length+' outlets']].map(x=>h('article',{key:x[0]},h('span',null,'REPORT'),h('b',null,x[0]),h('p',null,x[1]),h('button',null,'Open report →')))))}
function Users(){const[rows,setRows]=React.useState([]),[error,setError]=React.useState('');
React.useEffect(()=>{api('users').then(r=>setRows(r.users||[])).catch(()=>setError('User list could not be loaded.'))},[]);
return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'RBAC'),h('h1',null,'Users & access'),h('p',null,'Founder retains full control; each role sees only its operating scope.')),error?h('div',{className:'authError'},error):null,h(DataTable,{rows,cols:[['name','User'],['email','Email'],['role_name','Role'],['active','Active'],['must_change_password','Password change']],empty:'No users found.'}),h('div',{className:'notice'},h('b',null,'Production security active'),h('span',null,'Passwords are hashed in MySQL, first-login change is enforced, sessions are HTTP-only and actions are audit logged.')))}
function Crud({title,desc,rows,fields,onAdd,cols}){const[form,setForm]=React.useState(Object.fromEntries(fields.map(x=>[x[0],'' ])));function add(){onAdd(form);setForm(Object.fromEntries(fields.map(x=>[x[0],'' ])))}return h(React.Fragment,null,h('section',{className:'moduleHead'},h('small',null,'OPERATIONS'),h('h1',null,title),h('p',null,desc)),h('section',{className:'panel formrow'},fields.map(([k,l,t])=>h(Field,{key:k,label:l,value:form[k],type:t||'text',onChange:v=>setForm({...form,[k]:v})})),h('button',{className:'primary fit',onClick:add},'Add record')),h(DataTable,{rows,cols,empty:'No records yet.'}))}
function DataTable({rows,cols,empty}){if(!rows.length)return h(Empty,{text:empty});return h('div',{className:'tablewrap panel'},h('table',null,h('thead',null,h('tr',null,cols.map(c=>h('th',{key:c[0]},c[1])))),h('tbody',null,rows.map((r,i)=>h('tr',{key:r.id||i},cols.map(c=>h('td',{key:c[0]},c[2]?c[2](r[c[0]]):String(r[c[0]]??''))))))))}
ReactDOM.createRoot(document.getElementById('root')).render(h(Shell));
})();