-- Tea Shop BD Business OS / MySQL 8+ foundation schema
CREATE TABLE roles (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, role_id BIGINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, email VARCHAR(190) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, must_change_password TINYINT(1) DEFAULT 1, active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE franchises (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, code VARCHAR(30) UNIQUE NOT NULL, name VARCHAR(150) NOT NULL, district VARCHAR(100), upazila VARCHAR(100), status ENUM('pipeline','setup','active','watch','critical','closed') DEFAULT 'pipeline', margin_mode ENUM('tier','manual') DEFAULT 'tier', margin_percent DECIMAL(5,2) DEFAULT 25.00, opened_at DATE NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE products (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sku VARCHAR(50) UNIQUE NOT NULL, name VARCHAR(160) NOT NULL, category VARCHAR(80) NOT NULL, purchase_cost_per_kg DECIMAL(12,2) DEFAULT 0, active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE product_packs (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL, grams INT NOT NULL, packaging_bom JSON NULL, mrp DECIMAL(12,2) NOT NULL, active TINYINT(1) DEFAULT 1, FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE inventory_ledger (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, location_type ENUM('central','franchise') NOT NULL, location_id BIGINT UNSIGNED NULL, product_pack_id BIGINT UNSIGNED NOT NULL, movement_type VARCHAR(40) NOT NULL, qty DECIMAL(12,3) NOT NULL, reference_type VARCHAR(40), reference_id BIGINT UNSIGNED NULL, batch_no VARCHAR(80), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_pack_id) REFERENCES product_packs(id));
CREATE TABLE pos_sales (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, franchise_id BIGINT UNSIGNED NOT NULL, receipt_no VARCHAR(60) UNIQUE NOT NULL, gross_amount DECIMAL(12,2) NOT NULL, eligible_amount DECIMAL(12,2) NOT NULL, margin_percent DECIMAL(5,2) NOT NULL, earned_margin DECIMAL(12,2) NOT NULL, payment_method VARCHAR(30), sold_at DATETIME NOT NULL, FOREIGN KEY(franchise_id) REFERENCES franchises(id));
CREATE TABLE settlements (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, franchise_id BIGINT UNSIGNED NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, opening_stock_value DECIMAL(12,2) DEFAULT 0, stock_received_value DECIMAL(12,2) DEFAULT 0, verified_sales DECIMAL(12,2) DEFAULT 0, approved_returns DECIMAL(12,2) DEFAULT 0, stock_adjustment DECIMAL(12,2) DEFAULT 0, closing_stock_value DECIMAL(12,2) DEFAULT 0, earned_margin DECIMAL(12,2) DEFAULT 0, net_payable DECIMAL(12,2) DEFAULT 0, status ENUM('draft','review','approved','locked','paid') DEFAULT 'draft', FOREIGN KEY(franchise_id) REFERENCES franchises(id));
CREATE TABLE performance_share_rules (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, person_key VARCHAR(60) NOT NULL, tier VARCHAR(30) NOT NULL, percent DECIMAL(5,2) NOT NULL, effective_from DATE NOT NULL, effective_to DATE NULL, approved_by BIGINT UNSIGNED NULL);
CREATE TABLE finance_ledger (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, entry_date DATE NOT NULL, division VARCHAR(60) NOT NULL, account_code VARCHAR(40) NOT NULL, entry_type ENUM('debit','credit') NOT NULL, amount DECIMAL(12,2) NOT NULL, reference_type VARCHAR(40), reference_id BIGINT UNSIGNED NULL, memo VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE audit_logs (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id VARCHAR(80), before_json JSON NULL, after_json JSON NULL, ip_address VARCHAR(64), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
