import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
type Role='OWNER'|'OPERATIONS'|'FINANCE'|'WAREHOUSE'|'PRODUCTION'|'QC'|'PACKAGING'|'REGIONAL'|'FRANCHISE'|'OUTLET_MANAGER'|'CASHIER'|'AUDITOR';
const users=[
['Owner / Super Admin','owner@teashop.bd','OWNER'],
['Franchise & Retail Operations','operations@teashop.bd','OPERATIONS'],
['Finance & Accounts','finance@teashop.bd','FINANCE'],
['Warehouse & Inventory','warehouse@teashop.bd','WAREHOUSE'],
['Production & Blending','production@teashop.bd','PRODUCTION'],
['Quality Control','qc@teashop.bd','QC'],
['Packaging','packaging@teashop.bd','PACKAGING'],
['Regional Manager','regional@teashop.bd','REGIONAL'],
['Franchise Owner','franchise@teashop.bd','FRANCHISE'],
['Outlet Manager','manager@teashop.bd','OUTLET_MANAGER'],
['POS / Cashier','cashier@teashop.bd','CASHIER'],
['Auditor / Read Only','auditor@teashop.bd','AUDITOR']
] as const;
const nav=['Dashboard','Tea','Purchase & Suppliers','Blending & Production','QC & Wastage','Packaging','Products / SKU','Pricing Engine','Inventory / Warehouse','Outlets / Franchise','Franchise & Retail Operations','POS / Sales','Margin & Settlement','Finance & Accounts','Profit & Loss','Performance & Incentives','Customers','Corporate / B2B','Logistics','Reports','Approvals','Documents','Notifications','Users & Roles','Audit Log','Settings'];
const products=[['Royal Gold','CTC',450,500,449],['Premium CTC Luxury','CTC',600,500,579],['Premium Green Tea','Green',1400,100,349],['Dragon Well Tea','Green',5000,100,899],['Golden Leaf','Leaf Black',1800,100,399],['Silver Needles','White',17000,30,899]] as const;
const money=(n:number)=>'৳'+Math.round(n).toLocaleString('en-BD');
function Login({go}:{go:(u:any)=>void}){const[email,setEmail]=useState('owner@teashop.bd');const[p,setP]=useState('123456');function submit(e:any){e.preventDefault();const u=users.find(x=>x[1]===email);if(u&&p==='123456')go(u);else alert('Use a demo account with password 123456.')}return <div className="login"><section><div className="logo">T</div><small>TEA SHOP BD · BUSINESS OS</small><h1>One command center.<br/>Every outlet accountable.</h1><p>Raw tea, production, packaging, inventory, franchise, POS, settlement and finance—under founder control.</p></section><form onSubmit={submit}><div className="mini">T</div><h2>Welcome back</h2><p>Sign in to your secure workspace.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label><button className="primary">Sign in →</button><div className="demos"><b>Demo accounts</b>{users.map(u=><button type="button" onClick={()=>setEmail(u[1])}><span>{u[0]}</span><small>{u[1]}</small></button>)}<em>Password: 123456 · demo only</em></div></form></div>}
function App(){const[user,setUser]=useState<any>(null);const[page,setPage]=useState('Dashboard');if(!user)return <Login go={u=>{setUser(u);setPage(u[2]==='CASHIER'?'POS / Sales':'Dashboard')}}/>;return <div className="app"><aside><div className="brand"><div className="logo small">T</div><div><b>Tea Shop BD</b><span>Business OS</span></div></div><div className="role"><small>SECURE SESSION</small><b>{user[0]}</b><span>{user[2]}</span></div><nav>{nav.map(n=><button className={page===n?'active':''} onClick={()=>setPage(n)}>{n}</button>)}</nav><button className="logout" onClick={()=>setUser(null)}>Sign out</button></aside><main><header><div><small>TEA SHOP BD / {page.toUpperCase()}</small><h2>{page}</h2></div><div className="avatar">{user[0].split(' ').map((x:string)=>x[0]).slice(0,2)}</div></header>{page==='Dashboard'?<Overview/>:page==='POS / Sales'?<POS/>:<Module name={page}/>}</main></div>}
function Overview(){const rows=useMemo(()=>products.map(p=>{const raw=p[2]*p[3]/1000,pack=p[3]===500?28:p[3]===30?60:22,landed=raw+pack+12+raw*.03,fr=p[4]*.30,company=p[4]-fr;return{p,raw,landed,fr,company,ok:company>landed}}),[]);return <><section className="hero"><div><small>NETWORK COMMAND CENTER</small><h1>Tea Shop BD command center.</h1><p>Verified sales, stock accountability, outlet health and unit economics—without losing founder control.</p></div><div className="goal"><span>NETWORK GOAL</span><b>12 <em>/ 150</em></b><small>healthy outlets</small></div></section><div className="stats"><Card t="Verified sales · Oct" v="৳8.42L" s="+12.8% vs Sep"/><Card t="Company contribution" v="৳2.31L" s="After franchise earning"/><Card t="Outlet stock value" v="৳4.86L" s="Full account value"/><Card t="Settlement health" v="96.4%" s="3 accounts need review"/></div><div className="two"><section className="panel"><Title t="Franchise margin engine" tag="POLICY"/><div className="tiers">{[['25%','Starter'],['27%','Growth'],['30%','Elite'],['Manual','Owner override']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section><section className="panel"><Title t="Franchise & Retail Operations performance share" tag="OWNER CONTROL"/><div className="tiers three">{[['15%','Base'],['20%','Growth'],['25%','Elite']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><p className="hint">On positive distributable Franchise Division profit only—not MRP, stock issued or gross sales.</p></section></div><section className="panel"><Title t="A–Z unit economics preview" tag="PRICING ENGINE"/><div className="table"><table><thead><tr><th>SKU</th><th>Tea/kg</th><th>Pack</th><th>Raw tea</th><th>Est. landed</th><th>MRP</th><th>Franchise 30%</th><th>Company after franchise</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr><td><b>{r.p[0]}</b><small>{r.p[1]}</small></td><td>{money(r.p[2])}</td><td>{r.p[3]}g</td><td>{money(r.raw)}</td><td>{money(r.landed)}</td><td><b>{money(r.p[4])}</b></td><td>{money(r.fr)}</td><td>{money(r.company)}</td><td><i className={r.ok?'ok':'warn'}>{r.ok?'Healthy':'Review'}</i></td></tr>)}</tbody></table></div></section></>}
function Module({name}:{name:string}){const map:any={'Purchase & Suppliers':['Supplier & garden master','Purchase orders / GRN','Batch & lot traceability','Purchase price history'],'Blending & Production':['Production batches','Blend access control','Wastage recording','QC & yield variance'],'Packaging':['Packaging material stock','Pack-size BOM','Rebuild / repack orders','Labour & sealing cost'],'Inventory / Warehouse':['Central stock','Franchise stock ledger','Transfers & receiving','Barcode / damage / returns'],'Outlets / Franchise':['Applications & onboarding','25/27/30% tiers','Manual margin override','Outlet health & territory'],'Margin & Settlement':['Verified POS sales','Earned franchise margin','Opening/closing stock','Month close & lock'],'Finance & Accounts':['Income & expenses','Franchise Division P&L','VAT/tax provision','Management performance share & Tea Shop BD net'],Reports:['Sales & SKU profitability','Stock & wastage','Settlement aging','Regional performance'],'Users & Roles':['Users & roles','Location scope','Approval authority','Audit history']};const items=map[name]||['Workspace foundation'];return <><section className="module"><small>TEA SHOP BD BUSINESS OS</small><h1>{name}</h1><p>Founder-controlled workflow with role permissions, approvals and audit-ready records.</p></section><div className="features">{items.map((x:string,i:number)=><article><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><p>Production-ready workflow foundation for this module.</p><button>Open workspace →</button></article>)}</div><div className="notice"><b>Foundation connected</b><span>Database writes will be enabled after secure cPanel API/database credentials are configured.</span></div></>}
function POS(){const[cart,setCart]=useState<any[]>([]);const items=[['Royal Gold 500g',449],['Classic Blend 500g',399],['Premium Green 100g',349],['Golden Leaf 100g',399],['Mint Breeze 50g',249],['Chamomile 30g',399]];const total=cart.reduce((s,x)=>s+x[1],0);return <div className="pos"><section className="panel"><Title t="Point of Sale" tag="OUTLET 001"/><input className="search" placeholder="Search or scan barcode…"/><div className="products">{items.map(x=><button onClick={()=>setCart(c=>[...c,x])}><small>TEA SHOP BD</small><b>{x[0]}</b><strong>{money(x[1] as number)}</strong></button>)}</div></section><section className="panel cart"><Title t="Current sale" tag={cart.length+' ITEMS'}/>{cart.map((x,i)=><div className="line"><span>{x[0]}</span><b>{money(x[1])}</b><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}>×</button></div>)}<div className="total"><span>Total</span><b>{money(total)}</b></div><button className="primary" disabled={!cart.length}>Take payment →</button></section></div>}
function Card({t,v,s}:any){return <div className="card"><span>{t}</span><b>{v}</b><small>{s}</small></div>}function Title({t,tag}:any){return <div className="title"><h3>{t}</h3><span>{tag}</span></div>}
createRoot(document.getElementById('root')!).render(<App/>);